version: '3.7'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: ecom
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 4482:3306

volumes:
  mysql-data:
